language: r
dist: trusty
cache: packages
sudo: false

r: 3.5.1

r_check_args: "--no-build-vignettes --no-manual --as-cran --no-tests
--no-examples"

r_packages:
  - covr
  - devtools
  - testthat

bioc_packages:
  - GenomicRanges

r_github_packages:
  - mskilab/gUtils

before_install:
  - curl -OL https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE

script:
  - travis_wait 30 ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - travis_wait Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
